
module Events


  # @author Asirad
  # Class to handle basic action of events e.g. map keys
  class Basic
    
    
    # Map name of key to it number
    # @param [String|Symbol] name Name of event
    # @note Names are used from Android API (KeyEvent Class)
    # @todo Write all codes from Android API
    def map_key(name)
      case name.to_s
      when "KEYCODE_0"                  then return "7"
      when "KEYCODE_1"                  then return "8"
      when "KEYCODE_2"                  then return "9"
      when "KEYCODE_3"                  then return "10"
      when "KEYCODE_3D_MODE"            then return "206"
      when "KEYCODE_4"                  then return "11"
      when "KEYCODE_5"                  then return "12"
      when "KEYCODE_6"                  then return "13"
      when "KEYCODE_7"                  then return "14"
      when "KEYCODE_8"                  then return "15"
      when "KEYCODE_9"                  then return "16"
      when "KEYCODE_A"                  then return "29"
      when "KEYCODE_ALT_LEFT"           then return "57"
      when "KEYCODE_ALT_RIGHT"          then return "58"
      when "KEYCODE_APOSTROPHE"         then return "75"
      when "KEYCODE_APP_SWITCH"         then return "187"
      when "KEYCODE_AT"                 then return "77"
      when "KEYCODE_AVR_INPUT"          then return "182"
      when "KEYCODE_AVR_POWER"          then return "181"
      when "KEYCODE_B"                  then return "30"
      when "KEYCODE_BACK"               then return "4"
      when "KEYCODE_BACKSLASH"          then return "73"
      when "KEYCODE_BOOKMARK"           then return "174"
      when "KEYCODE_BREAK"              then return "121"
      when "KEYCODE_BUTTON_1"           then return "188"
      when "KEYCODE_BUTTON_10"          then return "197"
      when "KEYCODE_BUTTON_11"          then return "198"
      when "KEYCODE_BUTTON_12"          then return "199"
      when "KEYCODE_BUTTON_13"          then return "200"
      when "KEYCODE_BUTTON_14"          then return "201"
      when "KEYCODE_BUTTON_15"          then return "202"
      when "KEYCODE_BUTTON_16"          then return "203"
      when "KEYCODE_BUTTON_2"           then return "189"
      when "KEYCODE_BUTTON_3"           then return "190"
      when "KEYCODE_BUTTON_4"           then return "191"
      when "KEYCODE_BUTTON_5"           then return "192"
      when "KEYCODE_BUTTON_6"           then return "193"
      when "KEYCODE_BUTTON_7"           then return "194"
      when "KEYCODE_BUTTON_7"           then return "194"
      when "KEYCODE_BUTTON_8"           then return "195"
      when "KEYCODE_BUTTON_9"           then return "196"
      when "KEYCODE_BUTTON_A"           then return "96"
      when "KEYCODE_BUTTON_B"           then return "97"
      when "KEYCODE_BUTTON_C"           then return "98"
      when "KEYCODE_BUTTON_L1"          then return "102"
      when "KEYCODE_BUTTON_L2"          then return "104"
      when "KEYCODE_BUTTON_MODE"        then return "110"
      when "KEYCODE_BUTTON_R1"          then return "103"
      when "KEYCODE_BUTTON_R2"          then return "105"
      when "KEYCODE_BUTTON_SELECT"      then return "109"
      when "KEYCODE_BUTTON_START"       then return "108"
      when "KEYCODE_BUTTON_THUMBL"      then return "106"
      when "KEYCODE_BUTTON_THUMBR"      then return "107"
      when "KEYCODE_BUTTON_X"           then return "99"
      when "KEYCODE_BUTTON_Y"           then return "100"
      when "KEYCODE_BUTTON_Z"           then return "101"
      when "KEYCODE_C"                  then return "31"
      when "KEYCODE_CALL"               then return "5"
      when "KEYCODE_CAMERA"             then return "27"
      when "KEYCODE_CAPS_LOCK"          then return "115"
      when "KEYCODE_CAPTIONS"           then return "175"
      when "KEYCODE_CHANNEL_DOWN"       then return "167"
      when "KEYCODE_CHANNEL_UP"         then return "166"
      when "KEYCODE_CLEAR"              then return "28"
      when "KEYCODE_COMMA"              then return "55"
      when "KEYCODE_CTRL_LEFT"          then return "113"
      when "KEYCODE_CTRL_RIGHT"         then return "114"
      when "KEYCODE_D"                  then return "32"
      when "KEYCODE_DEL"                then return "67"
      when "KEYCODE_DPAD_CENTER"        then return "23"
      when "KEYCODE_DPAD_DOWN"          then return "20"
      when "KEYCODE_DPAD_LEFT"          then return "21"
      when "KEYCODE_DPAD_RIGHT"         then return "22"
      when "KEYCODE_DPAD_UP"            then return "19"
      when "KEYCODE_DVR"                then return "173"
      when "KEYCODE_E"                  then return "33"
      when "KEYCODE_ENDCALL"            then return "6"
      when "KEYCODE_ENTER"              then return "66"
      when "KEYCODE_ENVELOPE"           then return "65"
      when "KEYCODE_EQUALS"             then return "70"
      when "KEYCODE_ESCAPE"             then return "111"
      when "KEYCODE_EXPLORER"           then return "64"
      when "KEYCODE_F"                  then return "34"
      when "KEYCODE_F1"                 then return "131"
      when "KEYCODE_F10"                then return "140"
      when "KEYCODE_F11"                then return "141"
      when "KEYCODE_F12"                then return "142"
      when "KEYCODE_F2"                 then return "132"
      when "KEYCODE_F3"                 then return "133"
      when "KEYCODE_F4"                 then return "134"
      when "KEYCODE_F5"                 then return "135"
      when "KEYCODE_F6"                 then return "136"
      when "KEYCODE_F7"                 then return "137"
      when "KEYCODE_F8"                 then return "138"
      when "KEYCODE_F9"                 then return "139"
      when "KEYCODE_FOCUS"              then return "80"
      when "KEYCODE_FORWARD"            then return "125"
      when "KEYCODE_FORWARD_DEL"        then return "112"
      when "KEYCODE_FUNCTION"           then return "119"
      when "KEYCODE_G"                  then return "35"
      when "KEYCODE_GRAVE"              then return "68"
      when "KEYCODE_GUIDE"              then return "172"
      when "KEYCODE_H"                  then return "36"
      when "KEYCODE_HEADSETHOOK"        then return "79"
      when "KEYCODE_HOME"               then return "3"
      when "KEYCODE_I"                  then return "37"
      when "KEYCODE_INFO"               then return "165"
      when "KEYCODE_INSERT"             then return "124"
      when "KEYCODE_J"                  then return "38"
      when "KEYCODE_K"                  then return "39"
      when "KEYCODE_L"                  then return "40"
      when "KEYCODE_LANGUAGE_SWITCH"    then return "204"
      when "KEYCODE_LEFT_BRACKET"       then return "71"
      when "KEYCODE_M"                  then return "41"
      when "KEYCODE_MANNER_MODE"        then return "205"
      when "KEYCODE_MEDIA_CLOSE"        then return "128"
      when "KEYCODE_MEDIA_EJECT"        then return "129"
      when "KEYCODE_MEDIA_FAST_FORWARD" then return "90"
      when "KEYCODE_MEDIA_NEXT"         then return "87"
      when "KEYCODE_MEDIA_PAUSE"        then return "127"
      when "KEYCODE_MEDIA_PLAY"         then return "126"
      when "KEYCODE_MEDIA_PLAY_PAUSE"   then return "85"
      when "KEYCODE_MEDIA_PREVIOUS"     then return "88"
      when "KEYCODE_MEDIA_RECORD"       then return "130"
      when "KEYCODE_MEDIA_REWIND"       then return "89"
      when "KEYCODE_MEDIA_STOP"         then return "86"
      when "KEYCODE_MENU"               then return "82"
      when "KEYCODE_META_LEFT"          then return "117"
      when "KEYCODE_META_RIGHT"         then return "118"
      when "KEYCODE_MINUS"              then return "69"
      when "KEYCODE_MOVE_END"           then return "123"
      when "KEYCODE_MOVE_HOME"          then return "122"
      when "KEYCODE_MUTE"               then return "91"
      when "KEYCODE_N"                  then return "42"
      when "KEYCODE_NOTIFICATION"       then return "83"
      when "KEYCODE_NUM"                then return "78"
      when "KEYCODE_NUMPAD_0"           then return "144"
      when "KEYCODE_NUMPAD_1"           then return "145"
      when "KEYCODE_NUMPAD_2"           then return "146"
      when "KEYCODE_NUMPAD_3"           then return "147"
      when "KEYCODE_NUMPAD_4"           then return "148"
      when "KEYCODE_NUMPAD_5"           then return "149"
      when "KEYCODE_NUMPAD_6"           then return "150"
      when "KEYCODE_NUMPAD_7"           then return "151"
      when "KEYCODE_NUMPAD_8"           then return "152"
      when "KEYCODE_NUMPAD_9"           then return "153"
      when "KEYCODE_NUMPAD_ADD"         then return "157"
      when "KEYCODE_NUMPAD_COMMA"       then return "159"
      when "KEYCODE_NUMPAD_DIVIDE"      then return "154"
      when "KEYCODE_NUMPAD_DOT"         then return "158"
      when "KEYCODE_NUMPAD_ENTER"       then return "160"
      when "KEYCODE_NUMPAD_EQUALS"      then return "161"
      when "KEYCODE_NUMPAD_LEFT_PAREN"  then return "162"
      when "KEYCODE_NUMPAD_MULTIPLY"    then return "155"
      when "KEYCODE_NUMPAD_RIGHT_PAREN" then return "163"
      when "KEYCODE_NUMPAD_SUBTRACT"    then return "156"
      when "KEYCODE_NUM_LOCK"           then return "143"
      when "KEYCODE_O"                  then return "43"
      when "KEYCODE_P"                  then return "44"
      when "KEYCODE_PAGE_DOWN"          then return "93"
      when "KEYCODE_PAGE_UP"            then return "92"
      when "KEYCODE_PERIOD"             then return "56"
      when "KEYCODE_PICTSYMBOLS"        then return "94"
      when "KEYCODE_PLUS"               then return "81"
      when "KEYCODE_POUND"              then return "18"
      when "KEYCODE_POWER"              then return "26"
      when "KEYCODE_PROG_BLUE"          then return "186"
      when "KEYCODE_PROG_GREEN"         then return "184"
      when "KEYCODE_PROG_RED"           then return "183"
      when "KEYCODE_PROG_YELLOW"        then return "185"
      when "KEYCODE_Q"                  then return "45"
      when "KEYCODE_R"                  then return "46"
      when "KEYCODE_RIGHT_BRACKET"      then return "72"
      when "KEYCODE_S"                  then return "47"
      when "KEYCODE_SCROLL_LOCK"        then return "116"
      when "KEYCODE_SEARCH"             then return "84"
      when "KEYCODE_SEMICOLON"          then return "74"
      when "KEYCODE_SETTINGS"           then return "176"
      when "KEYCODE_SHIFT_LEFT"         then return "59"
      when "KEYCODE_SHIFT_RIGHT"        then return "60"
      when "KEYCODE_SLASH"              then return "76"
      when "KEYCODE_SOFT_LEFT"          then return "1"
      when "KEYCODE_SOFT_RIGHT"         then return "2"
      when "KEYCODE_SPACE"              then return "62"
      when "KEYCODE_STAR"               then return "17"
      when "KEYCODE_STB_INPUT"          then return "180"
      when "KEYCODE_STB_POWER"          then return "179"
      when "KEYCODE_SWITCH_CHARSET"     then return "95"
      when "KEYCODE_SYM"                then return "63"
      when "KEYCODE_SYSRQ"              then return "120"
      when "KEYCODE_T"                  then return "48"
      when "KEYCODE_TAB"                then return "61"
      when "KEYCODE_TV"                 then return "170"
      when "KEYCODE_TV_INPUT"           then return "178"
      when "KEYCODE_TV_POWER"           then return "177"
      when "KEYCODE_U"                  then return "49"
      when "KEYCODE_UNKNOWN"            then return "0"
      when "KEYCODE_V"                  then return "50"
      when "KEYCODE_VOLUME_DOWN"        then return "25"
      when "KEYCODE_VOLUME_MUTE"        then return "164"
      when "KEYCODE_VOLUME_UP"          then return "24"
      when "KEYCODE_W"                  then return "51"
      when "KEYCODE_WINDOW"             then return "171"
      when "KEYCODE_X"                  then return "52"
      when "KEYCODE_Y"                  then return "53"
      when "KEYCODE_Z"                  then return "54"
      when "KEYCODE_ZOOM_IN"            then return "168"
      when "KEYCODE_ZOOM_OUT"           then return "169"
      end
    end
    
    
    # Method to send text
    # @param [String] text This is a text to send
    def send_text(text)
      cmd = "input text #{text};"
      @move == "" ? @move = cmd : @move = @move + cmd
    end
    
    
  end
  
  
end
